<a href="https://colab.research.google.com/github/jeonggunlee/OpenSourceKeras/blob/master/01_oss_keras.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###한림대학교 소프트웨어 융합 대학 특강

##누구나 즐기는 딥러닝: 오픈소스 Keras를 활용하여!!!
---
이정근 교수

빅데이터전공주임/오픈소스소프트웨어센터장
소프트웨어융합대학

jeonggun.lee@hallym.ac.kr
2019년 5월

---
###단순 선형 회귀


## 단순 선형 회귀

**outcome = data * 2 + 1**에 대한 식의 패턴을 학습방식을 통하여 획득하는 방법을 Keras를 활용하여 공부해보도록 합시다!

입력데이터:
data = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

출력데이터:
outcome = [3, 5, 7, 9, 11, 13, 15, 17, 19, 21]

위와 같이 주어진 데이터를 이용하여 입력과 출력에 대한 패턴(알고리즘)을 찾아낼 수 있을까요 ?

In [2]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
outcome = np.array([3, 5, 7, 9, 11, 13, 15, 17, 19, 21])
print(data)
print(outcome)

[ 1  2  3  4  5  6  7  8  9 10]
[ 3  5  7  9 11 13 15 17 19 21]


입력데이터와 출력 outcome과의 관계를 그래프를 통해서 살펴볼까요 ?

그래프 사용을 위해서 matplotlib를 활용하여 봅시다!

In [3]:
import matplotlib.pylab as plt
plt.plot(data, outcome, 'rs--')
plt.show()

자, 이제 학습을 위해서 모델을 만들어 봅시다!

가장 쉽게 모델을 만드는 방법은 **Sequential**을 사용하는 것입니다.

차곡차곡, 입력부터 층을 만들어 나가는 방법이지요!

층의 속성도 여러가지가 있습니다만, 여기서는 가장 간단한 **Dense** type만 사용하겠습니다.

첫 모델에는 활성화 함수 (activation function)은 사용하지 않겠습니다. 이유를 아시나요 ? ^^


In [4]:
from keras.models import Sequential
from keras.layers import Dense

model = Sequential()
model.add(Dense(1, input_dim=1))

Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.


모델이 만들어 졌으면, 학습 및 최적화 방법에 대한 옵션을 기술하고, 모델을 Compile하겠습니다!

In [5]:
model.compile(loss='mean_squared_error', optimizer='adam')

자, 이제 학습을 진행해볼까요 ? 첫 학습을 위해서 **epochs**는 10번, **batch_size**는 1로 설정하여 진행하겠습니다.

In [9]:
model.fit(data, outcome, epochs=1000, batch_size=1)

Epoch 1/1000
10/10 [==============================] - 0s 799us/step - loss: 166.3599
Epoch 2/1000
10/10 [==============================] - 0s 799us/step - loss: 165.1551
Epoch 3/1000
10/10 [==============================] - 0s 800us/step - loss: 163.9434
Epoch 4/1000
10/10 [==============================] - 0s 700us/step - loss: 162.8840
Epoch 5/1000
10/10 [==============================] - 0s 700us/step - loss: 161.5592
Epoch 6/1000
10/10 [==============================] - 0s 999us/step - loss: 160.4924
Epoch 7/1000
10/10 [==============================] - 0s 800us/step - loss: 159.1831
Epoch 8/1000
10/10 [==============================] - 0s 699us/step - loss: 157.9636
Epoch 9/1000
10/10 [==============================] - 0s 999us/step - loss: 156.8466
Epoch 10/1000
10/10 [==============================] - 0s 900us/step - loss: 155.7385
Epoch 11/1000
10/10 [==============================] - 0s 899us/step - loss: 154.4771
Epoch 12/1000
10/10 [==============================] - 0s 1ms/s

Epoch 97/1000
10/10 [==============================] - 0s 600us/step - loss: 75.9823
Epoch 98/1000
10/10 [==============================] - 0s 600us/step - loss: 75.3225
Epoch 99/1000
10/10 [==============================] - 0s 600us/step - loss: 74.6190
Epoch 100/1000
10/10 [==============================] - 0s 799us/step - loss: 73.9288
Epoch 101/1000
10/10 [==============================] - 0s 800us/step - loss: 73.2133
Epoch 102/1000
10/10 [==============================] - 0s 799us/step - loss: 72.5268
Epoch 103/1000
10/10 [==============================] - 0s 1ms/step - loss: 71.8621
Epoch 104/1000
10/10 [==============================] - ETA: 0s - loss: 26.88 - 0s 700us/step - loss: 71.2506
Epoch 105/1000
10/10 [==============================] - 0s 700us/step - loss: 70.5758
Epoch 106/1000
10/10 [==============================] - 0s 799us/step - loss: 69.8967
Epoch 107/1000
10/10 [==============================] - 0s 799us/step - loss: 69.2051
Epoch 108/1000
10/10 [=============

10/10 [==============================] - 0s 600us/step - loss: 28.0868
Epoch 193/1000
10/10 [==============================] - 0s 899us/step - loss: 27.7890
Epoch 194/1000
10/10 [==============================] - 0s 700us/step - loss: 27.4099
Epoch 195/1000
10/10 [==============================] - 0s 699us/step - loss: 27.0858
Epoch 196/1000
10/10 [==============================] - 0s 700us/step - loss: 26.7557
Epoch 197/1000
10/10 [==============================] - 0s 799us/step - loss: 26.4284
Epoch 198/1000
10/10 [==============================] - 0s 800us/step - loss: 26.1133
Epoch 199/1000
10/10 [==============================] - 0s 600us/step - loss: 25.8006
Epoch 200/1000
10/10 [==============================] - 0s 700us/step - loss: 25.5030
Epoch 201/1000
10/10 [==============================] - 0s 799us/step - loss: 25.1481
Epoch 202/1000
10/10 [==============================] - 0s 600us/step - loss: 24.8921
Epoch 203/1000
10/10 [==============================] - 0s 600us/step

10/10 [==============================] - 0s 799us/step - loss: 7.5061
Epoch 288/1000
10/10 [==============================] - 0s 599us/step - loss: 7.3769
Epoch 289/1000
10/10 [==============================] - 0s 600us/step - loss: 7.2905
Epoch 290/1000
10/10 [==============================] - 0s 700us/step - loss: 7.1535
Epoch 291/1000
10/10 [==============================] - 0s 800us/step - loss: 7.0434
Epoch 292/1000
10/10 [==============================] - 0s 700us/step - loss: 6.9497
Epoch 293/1000
10/10 [==============================] - 0s 600us/step - loss: 6.8200
Epoch 294/1000
10/10 [==============================] - 0s 600us/step - loss: 6.7124
Epoch 295/1000
10/10 [==============================] - 0s 799us/step - loss: 6.6108
Epoch 296/1000
10/10 [==============================] - 0s 599us/step - loss: 6.5083
Epoch 297/1000
10/10 [==============================] - 0s 700us/step - loss: 6.4005
Epoch 298/1000
10/10 [==============================] - 0s 800us/step - loss: 6.

10/10 [==============================] - 0s 699us/step - loss: 1.5787
Epoch 384/1000
10/10 [==============================] - 0s 799us/step - loss: 1.5585
Epoch 385/1000
10/10 [==============================] - 0s 699us/step - loss: 1.5361
Epoch 386/1000
10/10 [==============================] - 0s 700us/step - loss: 1.5166
Epoch 387/1000
10/10 [==============================] - 0s 600us/step - loss: 1.4966
Epoch 388/1000
10/10 [==============================] - 0s 899us/step - loss: 1.4740
Epoch 389/1000
10/10 [==============================] - 0s 600us/step - loss: 1.4498
Epoch 390/1000
10/10 [==============================] - 0s 500us/step - loss: 1.4310
Epoch 391/1000
10/10 [==============================] - 0s 600us/step - loss: 1.4118
Epoch 392/1000
10/10 [==============================] - 0s 899us/step - loss: 1.3945
Epoch 393/1000
10/10 [==============================] - 0s 700us/step - loss: 1.3779
Epoch 394/1000
10/10 [==============================] - 0s 600us/step - loss: 1.

10/10 [==============================] - 0s 899us/step - loss: 0.7137
Epoch 480/1000
10/10 [==============================] - 0s 600us/step - loss: 0.7119
Epoch 481/1000
10/10 [==============================] - 0s 600us/step - loss: 0.7091
Epoch 482/1000
10/10 [==============================] - 0s 799us/step - loss: 0.7072
Epoch 483/1000
10/10 [==============================] - 0s 699us/step - loss: 0.7051
Epoch 484/1000
10/10 [==============================] - 0s 700us/step - loss: 0.7034
Epoch 485/1000
10/10 [==============================] - 0s 700us/step - loss: 0.7012
Epoch 486/1000
10/10 [==============================] - 0s 999us/step - loss: 0.6999
Epoch 487/1000
10/10 [==============================] - 0s 600us/step - loss: 0.6972
Epoch 488/1000
10/10 [==============================] - 0s 700us/step - loss: 0.6953
Epoch 489/1000
10/10 [==============================] - 0s 600us/step - loss: 0.6936
Epoch 490/1000
10/10 [==============================] - 0s 999us/step - loss: 0.

10/10 [==============================] - 0s 600us/step - loss: 0.5790
Epoch 576/1000
10/10 [==============================] - 0s 500us/step - loss: 0.5785
Epoch 577/1000
10/10 [==============================] - 0s 700us/step - loss: 0.5763
Epoch 578/1000
10/10 [==============================] - 0s 700us/step - loss: 0.5753
Epoch 579/1000
10/10 [==============================] - 0s 600us/step - loss: 0.5746
Epoch 580/1000
10/10 [==============================] - 0s 600us/step - loss: 0.5728
Epoch 581/1000
10/10 [==============================] - 0s 800us/step - loss: 0.5717
Epoch 582/1000
10/10 [==============================] - 0s 899us/step - loss: 0.5703
Epoch 583/1000
10/10 [==============================] - 0s 700us/step - loss: 0.5695
Epoch 584/1000
10/10 [==============================] - 0s 600us/step - loss: 0.5677
Epoch 585/1000
10/10 [==============================] - 0s 800us/step - loss: 0.5671
Epoch 586/1000
10/10 [==============================] - 0s 699us/step - loss: 0.

10/10 [==============================] - 0s 600us/step - loss: 0.4531
Epoch 672/1000
10/10 [==============================] - 0s 899us/step - loss: 0.4517
Epoch 673/1000
10/10 [==============================] - 0s 700us/step - loss: 0.4504
Epoch 674/1000
10/10 [==============================] - 0s 699us/step - loss: 0.4491
Epoch 675/1000
10/10 [==============================] - 0s 600us/step - loss: 0.4477
Epoch 676/1000
10/10 [==============================] - 0s 999us/step - loss: 0.4464
Epoch 677/1000
10/10 [==============================] - 0s 500us/step - loss: 0.4452
Epoch 678/1000
10/10 [==============================] - 0s 600us/step - loss: 0.4432
Epoch 679/1000
10/10 [==============================] - 0s 600us/step - loss: 0.4420
Epoch 680/1000
10/10 [==============================] - 0s 800us/step - loss: 0.4416
Epoch 681/1000
10/10 [==============================] - 0s 500us/step - loss: 0.4397
Epoch 682/1000
10/10 [==============================] - 0s 600us/step - loss: 0.

10/10 [==============================] - 0s 899us/step - loss: 0.3203
Epoch 768/1000
10/10 [==============================] - 0s 600us/step - loss: 0.3193
Epoch 769/1000
10/10 [==============================] - 0s 600us/step - loss: 0.3178
Epoch 770/1000
10/10 [==============================] - 0s 700us/step - loss: 0.3168
Epoch 771/1000
10/10 [==============================] - 0s 799us/step - loss: 0.3160
Epoch 772/1000
10/10 [==============================] - 0s 600us/step - loss: 0.3138
Epoch 773/1000
10/10 [==============================] - 0s 600us/step - loss: 0.3123
Epoch 774/1000
10/10 [==============================] - 0s 900us/step - loss: 0.3112
Epoch 775/1000
10/10 [==============================] - 0s 699us/step - loss: 0.3099
Epoch 776/1000
10/10 [==============================] - 0s 500us/step - loss: 0.3090
Epoch 777/1000
10/10 [==============================] - 0s 600us/step - loss: 0.3070
Epoch 778/1000
10/10 [==============================] - 0s 900us/step - loss: 0.

Epoch 863/1000
10/10 [==============================] - 0s 700us/step - loss: 0.2007
Epoch 864/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1995
Epoch 865/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1983
Epoch 866/1000
10/10 [==============================] - 0s 899us/step - loss: 0.1971
Epoch 867/1000
10/10 [==============================] - 0s 700us/step - loss: 0.1963
Epoch 868/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1953
Epoch 869/1000
10/10 [==============================] - 0s 700us/step - loss: 0.1939
Epoch 870/1000
10/10 [==============================] - ETA: 0s - loss: 0.152 - 0s 899us/step - loss: 0.1929
Epoch 871/1000
10/10 [==============================] - 0s 700us/step - loss: 0.1916
Epoch 872/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1908
Epoch 873/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1898
Epoch 874/1000
10/10 [===================

10/10 [==============================] - 0s 799us/step - loss: 0.1083
Epoch 959/1000
10/10 [==============================] - 0s 700us/step - loss: 0.1079
Epoch 960/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1066
Epoch 961/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1059
Epoch 962/1000
10/10 [==============================] - 0s 799us/step - loss: 0.1052
Epoch 963/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1047
Epoch 964/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1035
Epoch 965/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1028
Epoch 966/1000
10/10 [==============================] - 0s 899us/step - loss: 0.1019
Epoch 967/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1012
Epoch 968/1000
10/10 [==============================] - 0s 600us/step - loss: 0.1005
Epoch 969/1000
10/10 [==============================] - 0s 900us/step - loss: 0.

위의 학습 과정을 보면, epoch이 진행되기는 하지만 loss에 큰 변화가 없어보이네요. 

여러분, 어떻게 하면 좋을까요 ?

일단 학습된 모델을 가지고 새로운 data (20)에 대한 outcome을 예측해보도록 하겠습니다.

In [10]:
model.predict([20])

array([[39.84825]], dtype=float32)

답을 41로 예상을 하였는데, 생뚱 맞게 -6 정도가 나와 버렸네요.

학습을 제대로 하지 못한 경우겠지요 !

새로운 **epochs**과 **batch_size**로 학습을 다시 해보도록 하겠습니다. 여러분도 다양한 값들을 시도해보세요!

가장 적은 epoch으로 가장 적은 loss를 만들어 내는 분께 초코릿을 드리겠습니다!

In [0]:
model.fit(data, outcome, epochs=1000, batch_size=1)

Epoch 1/1000
10/10 [==============================] - 0s 3ms/step - loss: 212.4522
Epoch 2/1000
10/10 [==============================] - 0s 2ms/step - loss: 210.8506
Epoch 3/1000
10/10 [==============================] - 0s 2ms/step - loss: 209.4891
Epoch 4/1000
10/10 [==============================] - 0s 2ms/step - loss: 207.8287
Epoch 5/1000
10/10 [==============================] - 0s 2ms/step - loss: 206.0716
Epoch 6/1000
10/10 [==============================] - 0s 2ms/step - loss: 204.6000
Epoch 7/1000
10/10 [==============================] - 0s 2ms/step - loss: 202.9841
Epoch 8/1000
10/10 [==============================] - 0s 2ms/step - loss: 201.5959
Epoch 9/1000
10/10 [==============================] - 0s 3ms/step - loss: 199.9613
Epoch 10/1000
10/10 [==============================] - 0s 2ms/step - loss: 198.4021
Epoch 11/1000
10/10 [==============================] - 0s 2ms/step - loss: 196.9343
Epoch 12/1000
10/10 [==============================] - 0s 2ms/step - loss: 195.4823
E

Epoch이 진행되면서 지속적으로 loss도 떨어져서 낮은 loss를 갖도록 학습을 하였습니다. 

그럼 얼마나 잘 예측하는지 새로운 데이터를 가지고 예측을 해볼까요 ?

In [0]:
model.predict([20])

array([[40.304955]], dtype=float32)

아주 잘 예측하고 있음을 알 수 있습니다!



---


마지막으로 **가중치 (w)**와 **바이어스(b)**가 어떻게 찾아졌는지 살펴보도록 하겠습니다.

model.layers[n].get_weights()[0] : n 번째 layer의 가중차 값을 반환합니다.

model.layers[n].get_weights()[1]: n번째 layer의 바이어스 값을 반환합니다.

In [11]:
layer1_weight = model.layers[0].get_weights()[0]
layer1_bias = model.layers[0].get_weights()[1]

print(layer1_weight)
print(layer1_bias)

[[1.9124596]]
[1.5990585]


우리의 예상은 layer1_weight는 2, layer1_bias는 1이기를 기대하였지만, 조금 다른 값이 나온 것을 알 수 있습니다.

하지만, 꽤 잘 찾은 것 같지 않나요 ? ^^